; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	D:\PRATHAMESH\C_PROGRAMMING_LANGUAGE\TRY_OUT\pragma_pack_1.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_main
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; File d:\prathamesh\c_programming_language\try_out\pragma_pack_1.c
; Line 8
	push	ebp
	mov	ebp, esp
	sub	esp, 24					; 00000018H
; Line 13
	xor	eax, eax
; Line 14
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
